import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {MaterialLedger} from './game/material-ledger.js';
import {BuildSystem} from './game/build-system.js';
import './style.css';
import './guide.css';
import './mobile.css';

const canvas=document.querySelector('#game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x1b2428);scene.fog=new THREE.FogExp2(0x1b2428,.012);
const camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,300);camera.position.set(24,24,31);
const controls=new OrbitControls(camera,canvas);controls.target.set(0,2,0);controls.enableDamping=true;controls.maxPolarAngle=1.35;controls.minDistance=12;controls.maxDistance=65;
scene.add(new THREE.HemisphereLight(0xbcd9e8,0x4a3c24,2.2));const sun=new THREE.DirectionalLight(0xffe3b0,4);sun.position.set(-16,30,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-30;sun.shadow.camera.right=30;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;scene.add(sun);
const ground=new THREE.Mesh(new THREE.BoxGeometry(38,.8,27),new THREE.MeshStandardMaterial({color:0x806d50,roughness:.88}));ground.position.y=-.4;ground.receiveShadow=true;scene.add(ground);
const road=new THREE.Mesh(new THREE.PlaneGeometry(35,6),new THREE.MeshStandardMaterial({color:0x343a36,roughness:.72}));road.rotation.x=-Math.PI/2;road.position.set(0,.015,8);road.receiveShadow=true;scene.add(road);
const box=(w,h,d,color,x,y,z)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.62,metalness:.08}));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);return m};
for(let x=-18;x<=18;x+=3){box(2.7,1.5,.18,(x/3)%2?0xe9e5d1:0x17685e,x,.75,-13);box(2.7,1.5,.18,(x/3)%2?0xe9e5d1:0x17685e,x,.75,13)}for(let z=-10;z<=10;z+=3){box(.18,1.5,2.7,(z/3)%2?0xe9e5d1:0x17685e,-19,.75,z);box(.18,1.5,2.7,(z/3)%2?0xe9e5d1:0x17685e,19,.75,z)}
const sand=new THREE.Mesh(new THREE.ConeGeometry(4,2.5,32),new THREE.MeshStandardMaterial({color:0xc89a55,roughness:1}));sand.position.set(-11,1.25,-5);sand.scale.z=.75;sand.castShadow=true;scene.add(sand);
const mixer=box(4,1.2,3,0x2e3934,10,.6,-7);const drum=new THREE.Mesh(new THREE.CylinderGeometry(1.25,1.7,3,18),new THREE.MeshStandardMaterial({color:0xe1a02f,roughness:.45,metalness:.2}));drum.rotation.z=Math.PI/2;drum.position.set(10,2.1,-7);drum.castShadow=true;scene.add(drum);
const loader=new THREE.Group();const chassis=box(3,.8,2,0xe3a128,0,0,0);scene.remove(chassis);loader.add(chassis);chassis.position.y=1;const cab=box(1.5,1.5,1.7,0xdda02d,0,0,0);scene.remove(cab);loader.add(cab);cab.position.set(-.5,2,0);const bucket=box(1.5,.45,2.4,0x313733,0,0,0);scene.remove(bucket);loader.add(bucket);bucket.position.set(2.1,.75,0);for(const x of [-1,1])for(const z of [-1,1]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.58,.58,.55,16),new THREE.MeshStandardMaterial({color:0x171816,roughness:1}));w.rotation.x=Math.PI/2;w.position.set(x,.65,z*.95);w.castShadow=true;loader.add(w)}loader.position.set(-6,0,6);scene.add(loader);
const keys={};let bucketLoad=0,bucketLift=0;addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.code==='Space'&&!e.repeat)operateBucket()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);let last=performance.now();
const ledger=new MaterialLedger(),build=new BuildSystem(),materials=document.querySelector('#materials'),mission=document.querySelector('#mission'),toast=document.querySelector('#toast');let mode='drive',batch={sand:0,cement:0,water:0},mixed=null,ghost=null,placing=false,rightTimer=null;const formMeshes=new Map(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),workPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3(),particles=[],FORM_DIMS={foundation:[4,.55,2],column:[.7,3,.7],slab:[4,.4,4]};
document.querySelector('#help').addEventListener('click',()=>document.querySelector('#guide').classList.toggle('open'));
const joystick=document.querySelector('#joystick'),stick=joystick.querySelector('span');let touchDrive={forward:0,turn:0};function resetStick(){touchDrive={forward:0,turn:0};stick.style.transform='translate(0,0)'}joystick.addEventListener('pointerdown',e=>joystick.setPointerCapture(e.pointerId));joystick.addEventListener('pointermove',e=>{if(!joystick.hasPointerCapture(e.pointerId))return;const r=joystick.getBoundingClientRect(),x=THREE.MathUtils.clamp(e.clientX-(r.left+r.width/2),-42,42),y=THREE.MathUtils.clamp(e.clientY-(r.top+r.height/2),-42,42);touchDrive.turn=x/42;touchDrive.forward=-y/42;stick.style.transform=`translate(${x}px,${y}px)`});joystick.addEventListener('pointerup',resetStick);joystick.addEventListener('pointercancel',resetStick);
document.querySelectorAll('[data-touch]').forEach(btn=>{const key=btn.dataset.touch;btn.addEventListener('pointerdown',e=>{e.preventDefault();if(key==='space')operateBucket();else keys[key]=true});for(const event of ['pointerup','pointercancel','pointerleave'])btn.addEventListener(event,()=>{if(key!=='space')keys[key]=false})});
function notify(text){toast.textContent=text;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),1500)}
function refresh(){materials.innerHTML=`<b>铲斗 ${bucketLoad} / 100 L</b><br>搅拌斗：沙 ${batch.sand} L　水泥 ${batch.cement} L<br>水 ${batch.water} L　湿混凝土 ${Math.round(ledger.stock.concrete)} L`;const p=build.getProgress();mission.textContent=p.foundations<1?'任务 01 · 挖沙并配制混凝土':p.columns<4?`任务 02 · 浇筑立柱 ${p.columns}/4`:'任务 03 · 搭建二层楼板'}refresh();
function burst(pos,color,count=90){const geo=new THREE.SphereGeometry(.07,5,4),mat=new THREE.MeshStandardMaterial({color,roughness:1});for(let i=0;i<count;i++){const m=new THREE.Mesh(geo,mat);m.position.copy(pos);m.userData.v=new THREE.Vector3((Math.random()-.5)*3,Math.random()*3+1,(Math.random()-.5)*3);m.userData.life=1.4+Math.random();scene.add(m);particles.push(m)}}
function createForm(form){const dims=FORM_DIMS[form.type],mesh=box(...dims,0x8f9890,form.position.x,form.position.y+dims[1]/2,form.position.z);mesh.material.transparent=true;mesh.material.opacity=.48;mesh.userData.form=form;formMeshes.set(form.id,mesh)}
function cancelPlacement(){placing=false;if(ghost){scene.remove(ghost);ghost.geometry.dispose();ghost.material.dispose();ghost=null}notify('已取消摆放')}
function pointerToGround(e){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.ray.intersectPlane(workPlane,hit)}
function snappedPosition(type,pos){let x=build.snap(pos.x),z=build.snap(pos.z),best=1.15;for(const f of build.forms){const d=FORM_DIMS[f.type],candidates=[[f.position.x-d[0]/2,f.position.z-d[2]/2],[f.position.x+d[0]/2,f.position.z-d[2]/2],[f.position.x-d[0]/2,f.position.z+d[2]/2],[f.position.x+d[0]/2,f.position.z+d[2]/2],[f.position.x-d[0]/2,f.position.z],[f.position.x+d[0]/2,f.position.z],[f.position.x,f.position.z-d[2]/2],[f.position.x,f.position.z+d[2]/2]];for(const c of candidates){const distance=Math.hypot(pos.x-c[0],pos.z-c[1]);if(distance<best){best=distance;x=build.snap(c[0]);z=build.snap(c[1])}}}return{x,y:type==='slab'?3:0,z}}
function updateGhost(e){if(!placing||!pointerToGround(e))return;const p=snappedPosition(mode,hit),dims=FORM_DIMS[mode];if(!ghost){ghost=new THREE.Mesh(new THREE.BoxGeometry(...dims),new THREE.MeshStandardMaterial({color:0x83d06c,transparent:true,opacity:.38,depthWrite:false}));scene.add(ghost)}ghost.position.set(p.x,p.y+dims[1]/2,p.z);const occupied=build.forms.some(f=>f.position.x===p.x&&f.position.y===p.y&&f.position.z===p.z);ghost.material.color.set(occupied?0xe3523e:0x83d06c);ghost.userData.position=p}
function operateBucket(){if(mode!=='drive'){notify('先切换到“驾驶铲车”');return}const nearSand=loader.position.distanceTo(new THREE.Vector3(-11,0,-5))<5,nearMixer=loader.position.distanceTo(new THREE.Vector3(10,0,-7))<5;if(nearSand&&bucketLoad<100&&bucketLift<.35){bucketLoad=Math.min(100,bucketLoad+50);sand.scale.y=Math.max(.35,sand.scale.y-.08);burst(loader.localToWorld(new THREE.Vector3(2.2,.6,0)),0xc89a55,80);notify(`装入沙子 · 铲斗 ${bucketLoad}/100 L`)}else if(nearMixer&&bucketLoad>0){batch.sand+=bucketLoad;burst(new THREE.Vector3(10,3,-7),0xc89a55,120);notify(`卸入搅拌斗 +${bucketLoad} L`);bucketLoad=0}else notify(nearSand?'先按 E 降低铲斗再挖沙':'开到沙堆或搅拌机旁再按空格');refresh()}
document.querySelectorAll('#toolbar button').forEach(btn=>btn.addEventListener('click',()=>{cancelPlacement();document.querySelectorAll('#toolbar button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');mode=btn.dataset.mode;controls.enabled=!['foundation','column','slab'].includes(mode);if(mode==='cement'){batch.cement+=25;burst(new THREE.Vector3(10,3,-7),0xd8d2c5,45);notify('水泥加入 +25 L')}if(mode==='water'){batch.water+=12.5;burst(new THREE.Vector3(10,3,-7),0x76b7cf,60);notify('水阀开启 +12.5 L')}if(mode==='mix'){try{mixed=ledger.mixConcrete(batch);batch={sand:0,cement:0,water:0};notify(`搅拌完成 · 强度 ${Math.round(mixed.strength*100)}%`)}catch{notify('配料不足：推荐 200 沙 / 100 水泥 / 50 水')}mode='drive';controls.enabled=true;refresh()}}));
canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;if(['foundation','column','slab'].includes(mode)){placing=true;updateGhost(e);canvas.setPointerCapture(e.pointerId);return}if(mode!=='pour'||!pointerToGround(e))return;let nearest=[...build.forms].filter(f=>f.state!=='cured').sort((a,b)=>new THREE.Vector3(a.position.x,0,a.position.z).distanceToSquared(hit)-new THREE.Vector3(b.position.x,0,b.position.z).distanceToSquared(hit))[0];if(!nearest||ledger.stock.concrete<=0){notify('先搅拌混凝土，再点击模板浇筑');return}const amount=Math.min(80,ledger.stock.concrete),accepted=build.pour(nearest.id,amount,mixed?.strength||.6);ledger.consume('concrete',accepted);burst(new THREE.Vector3(nearest.position.x,3,nearest.position.z),0x6f756e,130);notify(`已浇筑 ${Math.round(accepted)} L`);refresh()});
canvas.addEventListener('pointermove',updateGhost);canvas.addEventListener('pointerup',e=>{if(!placing||e.button!==0||!ghost)return;placing=false;const result=build.placeForm(mode,ghost.userData.position);scene.remove(ghost);ghost.geometry.dispose();ghost.material.dispose();ghost=null;if(result.error)notify(result.error==='unsupported'?'楼板需要已凝固立柱支撑':'这里已有模板');else{createForm(result);notify('已吸附放置；右键双击可取消下一次摆放')}refresh()});
canvas.addEventListener('contextmenu',e=>{e.preventDefault();if(rightTimer){clearTimeout(rightTimer);rightTimer=null;cancelPlacement();mode='drive';controls.enabled=true;document.querySelector('[data-mode="drive"]').click();return}rightTimer=setTimeout(()=>{rightTimer=null;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);const target=raycaster.intersectObjects([...formMeshes.values()],false)[0]?.object;if(!target){notify('快速双击右键取消；单击构件拆除');return}const form=target.userData.form;build.remove(form.id);formMeshes.delete(form.id);scene.remove(target);notify(form.filled>0?'构件已返工拆除，混凝土不返还':'放错的模板已拆除');refresh()},280)});
function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000,.04);last=now;const forward=THREE.MathUtils.clamp((keys.w?1:0)-(keys.s?1:0)+touchDrive.forward,-1,1),turn=THREE.MathUtils.clamp((keys.a?1:0)-(keys.d?1:0)-touchDrive.turn,-1,1);loader.rotation.y+=turn*dt*1.7;loader.translateX(forward*dt*5);bucketLift=THREE.MathUtils.clamp(bucketLift+((keys.q?1:0)-(keys.e?1:0))*dt,.05,1.5);bucket.position.y=.55+bucketLift;bucket.rotation.z=-bucketLift*.28;drum.rotation.x+=dt*1.5;build.update(dt);for(const [id,m] of formMeshes){const f=m.userData.form;if(f.state==='wet')m.material.color.set(0x626961);if(f.state==='setting')m.material.opacity=.75;if(f.state==='cured'){m.material.opacity=1;m.material.color.set(0xb4b7ad)}}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.userData.v.y-=7*dt;p.position.addScaledVector(p.userData.v,dt);if(p.position.y<.08){p.position.y=.08;p.userData.v.multiplyScalar(.3)}p.userData.life-=dt;if(p.userData.life<=0){scene.remove(p);particles.splice(i,1)}}controls.update();renderer.render(scene,camera)}requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});setTimeout(()=>document.querySelector('#loading').style.display='none',500);
