(()=>{
const old=document.querySelector('#scene');old.remove();document.querySelector('#lens').remove();document.querySelector('#dust').remove();document.querySelector('#coords').remove();
document.querySelector('.copy').innerHTML='<div class="eyebrow">THE MEMORY OF A LIVING WORLD</div><h1><i>Where you touch,</i>life awakens.</h1><p>拂过枯木，让苔藓和微小的花重新生长。</p>';
document.querySelector('.hint').textContent='MOVE TO GROW · 生长痕迹会保留';
const style=document.createElement('style');style.textContent='.stage{background:#030405}.copy{top:15%;left:0;width:100%;max-width:none;text-align:center}.copy h1{font-size:clamp(48px,7vw,100px);line-height:.95}.copy h1 i{color:#eeeee8}.copy p{margin:25px auto 0}.noise{display:none}.growth-canvas{z-index:0;pointer-events:auto;touch-action:none}.growth-reset{position:absolute;z-index:20;bottom:30px;right:4%;padding:12px 20px;color:#e8ebde;background:#ffffff0d;border:1px solid #ffffff29;border-radius:30px;cursor:pointer}.growth-reset:focus-visible{outline:2px solid #afce8a;outline-offset:4px}@media(max-width:680px){.copy{top:17%;padding:0 20px}.copy h1{font-size:52px}.hint{left:24px;transform:none;font-size:8px}.growth-reset{bottom:55px}}';document.head.append(style);
const c=document.createElement('canvas');c.className='growth-canvas';c.setAttribute('aria-label','移动鼠标或手指，让枯木长出苔藓和小花');document.querySelector('.stage').prepend(c);const ctx=c.getContext('2d'),mask=document.createElement('canvas'),mc=mask.getContext('2d'),layer=document.createElement('canvas'),lc=layer.getContext('2d'),dry=new Image(),live=new Image();let w=0,h=0,d=1,fit={},ready=false,marks=[],lastPoint=null,raf=0,last=0;
function render(){if(!ready)return;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.drawImage(dry,fit.x,fit.y,dry.width*fit.s,dry.height*fit.s);lc.globalCompositeOperation='source-over';lc.clearRect(0,0,layer.width,layer.height);lc.drawImage(live,0,0);lc.globalCompositeOperation='destination-in';lc.drawImage(mask,0,0);ctx.drawImage(layer,fit.x,fit.y,layer.width*fit.s,layer.height*fit.s)}
function resize(){w=innerWidth;h=innerHeight;d=Math.min(devicePixelRatio||1,2);c.width=w*d;c.height=h*d;if(ready){const s=Math.max(w/dry.width,h/dry.height);fit={s,x:(w-dry.width*s)/2,y:(h-dry.height*s)/2};render()}}
function tick(now){raf=0;const dt=Math.min(40,last?now-last:16.67);last=now;for(const p of marks){p.age+=dt;const t=Math.min(1,p.age/1000),r=p.r*(.2+.8*(1-Math.pow(1-t,3))),g=mc.createRadialGradient(p.x,p.y,0,p.x,p.y,r);g.addColorStop(0,'rgba(255,255,255,.22)');g.addColorStop(.35,'rgba(255,255,255,.15)');g.addColorStop(.7,'rgba(255,255,255,.04)');g.addColorStop(1,'rgba(255,255,255,0)');mc.globalAlpha=dt/40;mc.fillStyle=g;mc.fillRect(p.x-r,p.y-r,r*2,r*2)}mc.globalAlpha=1;marks=marks.filter(p=>p.age<1450);render();if(marks.length)raf=requestAnimationFrame(tick);else last=0}
function grow(px,py){if(!ready)return;const p={x:(px-fit.x)/fit.s,y:(py-fit.y)/fit.s},r=Math.min(w,h)*.12/fit.s,n=lastPoint?Math.max(1,Math.ceil(Math.hypot(p.x-lastPoint.x,p.y-lastPoint.y)/(r*.23))):1;for(let i=1;i<=Math.min(n,30);i++){const t=i/Math.min(n,30);marks.push({x:lastPoint?lastPoint.x+(p.x-lastPoint.x)*t:p.x,y:lastPoint?lastPoint.y+(p.y-lastPoint.y)*t:p.y,r,age:0})}lastPoint=p;if(marks.length>200)marks.splice(0,marks.length-200);if(!raf)raf=requestAnimationFrame(tick)}
c.addEventListener('pointermove',e=>grow(e.clientX,e.clientY));c.addEventListener('pointerdown',e=>{lastPoint=null;c.setPointerCapture(e.pointerId);grow(e.clientX,e.clientY)});for(const ev of ['pointerleave','pointerup','pointercancel'])c.addEventListener(ev,()=>lastPoint=null);const reset=document.createElement('button');reset.className='growth-reset';reset.textContent='重新生长 ↗';reset.onclick=()=>{mc.clearRect(0,0,mask.width,mask.height);marks=[];lastPoint=null;render()};document.querySelector('.stage').append(reset);
Promise.all([new Promise((resolve,reject)=>{dry.onload=resolve;dry.onerror=reject;dry.src='dry-tree-v2.png'}),new Promise((resolve,reject)=>{live.onload=resolve;live.onerror=reject;live.src='living-tree-v2.png'})]).then(()=>{for(const a of [mask,layer]){a.width=dry.width;a.height=dry.height}ready=true;resize()}).catch(()=>{document.querySelector('.hint').textContent='树木纹理加载失败，请刷新'});addEventListener('resize',resize);resize();
})();
